#!/usr/bin/python

# Crowley-Dev // GITHUB
# TEAM: Albania-Security


import os, time
from sys import *
from subprocess import run


P = "\033[m" + "\033[1;30m"
V = "\033[m" + "\033[1;31m"
B = "\033[m" + "\033[1;37m"
C = "\033[m" + "\033[1;36m"
A = "\033[m" + "\033[1;33m"


def Warning( warning ):
	return ( B ) + "\n\n[" + ( V ) + f"{warning}" + ( B ) + "] " + ( C )


def clear():
	os.system("cls" if (os.name == "nt") else "clear");


def script( program ):
	os.system(f"bash {program}");


def update(): # Update by p0isonBr
	print( Warning( "!" ) + "Updating, please wait...\n\033[m");
	run(["git", "pull"]);time.sleep(1);


def banner():
	return f"""{V}
	 ┏━┓╺┳╸╻ ╻┏━╸┏┓╻┏━┓   ╺┳┓┏━┓╻ ╻
	 ┣━┫ ┃ ┣━┫┣╸ ┃┗┫┣━┫    ┃┃╺━┫┃┏┛
	 ╹ ╹ ╹ ╹ ╹┗━╸╹ ╹╹ ╹   ╺┻┛┗━┛┗┛

    {B}Script Coded By: {P}@AthenaD3V {B}// {P}GITHUB
"""


exit = 0
while ( exit < 1 ):
	clear();print( "\033[m",
			banner(),
			f"""
        {A}1 {B}>> ADMIN FINDER
        {A}2 {B}>> ENCRYPT FILE
        {A}3 {B}>> STALKING GITHUB
        {A}4 {B}>> GENERATE REVERSE SHELL
        {A}5 {B}>> DOWNLOAD YOUTUBE VIDEOS
	{A}6 {B}>> MORE...

	{A}U {B}>> UPDATE
	{A}E {B}>> EXIT
""");

	try:
		option = input( Warning( "+" ) + f"{B}Choose an option:{P} ").lower();


		if ( option == "1" or option == "01" ):
			script( ".CmFinder" );

		elif ( option == "2" or option == "02" ):
			script( ".obfuscate" );

		elif ( option == "3" or option == "03" ):
			script( ".InfoGit" );

		elif ( option == "4" or option == "04" ):
			script( ".ShellR");

		elif ( option == "5" or option == "05" ):
			script( ".YtDownload" );

		elif ( option == "6" or option == "06" ):
			script( ".ShellPlague" );

		elif ( option == "e" or option == "exit" ):
			exit += 1

		elif ( option == "u" or option == "update" ):
			update(); #restart();

		else:
			pass


	except KeyboardInterrupt:
		print( Warning( "!" ) + "Closing session...\033[m");
		exit()

	except Exception as error:
		print( Warning( "ERROR" ) + str( error ));
		exit()
